### ISSUE TITLE
Info that you need

### ISSUE THREAD

**Issue by easy-and-simple** [luismeruje/dockerized-gitlab#1]
These guys here are so toxic so I need to do such dumb things
You can get part of image as you want by using sensor object
sensor.set_windowing(roi)
roi is a rect tuple (x, y, w, h)

**Comment by luismeruje** [comment]
@easy-and-simple thank you so much for you suggestion. I know that method exists, but even before I can call it, if I tree setting the framesize to UXGA, as in sensor.set_framesize(sensor.UXGA) I get an out of memory error.
Doest the set_windowing method work for the full resolution without setting the framesize to UXGA?

**Comment by easy-and-simple** [comment]
OK try then to set first this method and then full resolution

**Comment by luismeruje** [comment]
Also I think that method as a TODO note on the source code.

**Comment by luismeruje** [comment]
Ok, I will try your suggestion as soon as I can.

**Comment by easy-and-simple** [comment]
I also will try to si what happens

**Comment by easy-and-simple** [comment]
windowing function is working but buffer allocation function should be fixed in code to make is works with max resolution and then build

**Comment by luismeruje** [comment]
@easy-and-simple I ended up being able to do it with the registers, but thank you anyway!
Turns out I had already gotten a valid set of registers for UXGA, but the image was very dark for some reason, so I thought the registers were wrong. I set exposure time manually and increased birghtness, and that solved my problem. After that I just had to move the window. I'll mark this issue as closed.
